/**
 * Englische UI-Texte bei `NEXT_PUBLIC_HTML_LANG=en`.
 * Fehlende Keys bleiben bei den deutschen `FORK_DEFAULTS.labels`.
 */
export const BRAND_LABELS_EN = {
  staffSingular: "Instructor",
  staffPlural: "Instructors",
  staffCollectivePlural: "Instructors",
  staffRoleInInvite: "instructor",
  clientSingular: "Guest",
  clientPlural: "Guests",
  serviceSingular: "Course",
  servicePlural: "Courses",
  bookingSingular: "Booking",
  bookingPlural: "Bookings",
  serviceTypeSingular: "Course type",
  serviceTypePlural: "Course types",
  requestServiceCta: "Request a course",
  teamLoginNav: "Login (team)",
  teamLoginHome: "Team login",
  teamAreaTitle: "Team area",
  appointmentSingular: "Appointment",
  appointmentPlural: "Appointments",
  bookingRequestSingular: "Booking request",
  bookingRequestPlural: "Booking requests",
  requestSingular: "Request",
  requestPlural: "Requests",
  invoiceSingular: "Invoice",
  invoicePlural: "Invoices",
  navCalendar: "Calendar",
  navInvoices: "Invoices",
  navChat: "Chat",
  navAdmin: "Admin",
  navAudit: "Audit",
  navAuditLog: "Audit log",
  navTeam: "Team",
  navSignOut: "Sign out",
  navSessionLoadingEllipsis: "…",
  navHome: "Home",
  navContact: "Contact",
  navPrivacy: "Privacy",
  navImpressum: "Legal notice",
  navDashboard: "Dashboard",
  clientSkillFilterLabel: "Level",
  chatPageIntroSegment1Template:
    "{navTeam} channels and direct messages. While ",
  chatPageIntroSegment2Template: " is running, the header shows ",
  chatPageIntroSegment3Template: "; otherwise it uses ",
  chatChannelsHeading: "Channels",
  chatDirectHeading: "Direct",
  chatConnectionLive: "Live (Socket.io)",
  chatConnectionPolling: "Polling",
  calNext: "Next",
  calPrevious: "Back",
  calToday: "Today",
  calMonth: "Month",
  calWeek: "Week",
  calDay: "Day",
  calAgenda: "Agenda",
  calDate: "Date",
  calTime: "Time",
  calShowMoreSuffix: "more",
  statusGeplant: "Scheduled",
  statusDurchgefuehrt: "Completed",
  statusStorniert: "Cancelled",
  statusOffen: "Open",
  statusBezahlt: "Paid",
  statusAnfrageNeu: "New",
  statusAnfrageBestaetigt: "Confirmed",
  statusAnfrageAbgelehnt: "Declined",
  uiErrorGeneric: "Error",
  uiSave: "Save",
  uiSaveInProgress: "Saving…",
  uiSaveFailed: "Could not save",
  uiDeleteFailed: "Could not delete",
  uiStatusUpdateFailed: "Could not update status",
  uiNameRequired: "Name is required",
  uiValidationNameAndEmail: "Name and a valid email are required.",
  placeholderClientSearch: "Name or email…",
  placeholderClientSearchModal: "Search name or email…",
  placeholderEmail: "Email",
  placeholderPhoneOptional: "Phone (optional)",
  uiCancel: "Cancel",
  uiEdit: "Edit",
  uiClose: "Close",
  toastSuccessOn: "Success toasts: on",
  toastSuccessOff: "Success toasts: off",
  toastInfoOn: "Info toasts: on",
  toastInfoOff: "Info toasts: off",
  toastSessionQuietOn: "Session quiet: on",
  toastSessionQuietOff: "Session quiet: off",
  toastSessionQuietBadge: "Session quiet active",
  uiRefresh: "Refresh",
  uiDelete: "Delete",
  uiContactTextRequired: "Text is required",
  fieldPrice: "Price",
  fieldStatus: "Status",
  fieldSource: "Source",
  fieldNotes: "Notes",
  fieldPaymentStatus: "Payment",
  fieldPaymentExternalRef: "Payment reference",
  bookingPaymentLabelNone: "Not recorded",
  bookingPaymentLabelDeposit: "Deposit",
  bookingPaymentLabelPaid: "Paid",
  bookingPaymentLabelRefunded: "Refunded",
  bookingActionStornieren: "Cancel booking",
  uiFilterAll: "All",
  invoiceStatsLoading: "Loading monthly stats…",
  invoiceMetricOpenMonth: "Open (month)",
  invoiceMetricPaidMonth: "Paid (month)",
  invoiceTableNumberAbbrev: "No.",
  invoiceTableDate: "Date",
  invoiceTableActions: "Actions",
  invoicePreview: "Preview",
  invoicePdfLink: "PDF",
  invoiceDownloadPdf: "Download PDF",
  invoiceMarkPaidButton: "Mark as paid",
  invoiceMarkedPaidToastTemplate: "{invoice} marked as paid.",
  apiUnauthorized: "Not signed in.",
  apiForbidden: "Permission denied.",
  apiNotFound: "Not found",
  apiValidationDefault: "Invalid input",
  apiTooManyRequests: "Too many requests. Please try again later.",
  adminRequestConfirm: "Confirm",
  adminRequestReject: "Decline",
  adminRequestConfirmedToastTemplate:
    "{bookingRequestSingular} confirmed and {bookingSingular} created.",
  adminRequestRejectedToastTemplate:
    "{bookingRequestSingular} declined.",
  adminBookingRequestAssignStaffTitleTemplate: "Assign {staffCollectivePlural}",
  adminBookingRequestConfirmCreateTemplate: "Create {bookingSingular}",
  adminBookingRequestRejectTitleTemplate: "Decline {bookingRequestSingular}",
  adminNoTeachersForRequestConfirmHint:
    "No active teacher or admin loaded. Under Admin → Users, invite or activate at least one teacher.",
  adminSelectStaffPlaceholder: "— Select person —",
  adminNewRequestToastTitleTemplate: "New {bookingRequest}",
  adminNewRequestToastBodyTemplate:
    "At least one new {requestSingular} has arrived.",
  adminNewRequestToastCtaTemplate: "Go to {requestPlural}",
  placeholderRejectReasonOptional: "Reason (optional)",
  auditLogUnauthorized: "Not signed in — please sign in again.",
  auditLogForbiddenTemplate: "No permission for {navAuditLog}.",
  uiLoadingEllipsis: "Loading…",
  uiNoEntriesYet: "No entries yet.",
  navPageLoadingTemplate: "Loading {navTitle}…",
  staffCollectiveListLoadingTemplate:
    "Loading {staffCollectivePlural} list…",
  staffListEmptyTemplate:
    "No {staffPlural} found. Invite {staffCollectivePlural} via {navAdmin} or check the database.",
  teacherLegendEmptyTemplate: "No active {staffPlural} loaded.",
  adminCourseTypesLoadingTemplate: "Loading {serviceTypePlural}…",
  adminCourseTypesEmptyTemplate:
    "No {serviceTypePlural} yet. Create one above or run seed/migrations.",
  adminCourseTypeCreateFailedTemplate:
    "Could not create {serviceTypeSingular}",
  calendarFilterShowAllStaffTemplate: "Show all {staffCollectivePlural}",
  calendarFilterTeacherByTemplate: "Filter {staffSingular}",
  publicWizardPickDate: "Pick a date",
  publicWizardTimeAndContact: "Time & contact",
  publicWizardSlotsTitle: "Time slots",
  publicAvailFree: "Free",
  publicAvailPartial: "Partial",
  publicAvailFull: "Full",
  publicApproxEndShort: "Ends approx.",
  calWeekdayMo: "Mon",
  calWeekdayDi: "Tue",
  calWeekdayMi: "Wed",
  calWeekdayDo: "Thu",
  calWeekdayFr: "Fri",
  calWeekdaySa: "Sat",
  calWeekdaySo: "Sun",
  placeholderFirstName: "First name",
  placeholderLastName: "Last name",
  placeholderMessageOptional: "Message (optional)",
  publicTurnstileLabel: "Security check",
  publicSummaryDateLabel: "Date",
  publicSummaryPriceLabel: "Price",
  publicNoPaymentDisclaimer:
    "No payment now — we confirm by email within 24 hours.",
  publicThanksTitleTemplate: "Thank you, {name}!",
  publicThanksIntroTemplate:
    "Your {request} was received. You will get a confirmation shortly at",
  publicReferenceLabel: "Reference",
  publicWizardSubmitRequestCtaTemplate: "Send {requestSingular} →",
  publicWizardNewRequestAgainTemplate: "Submit another {requestSingular}",
  guestBookingListPriceTemplate: "{currency} {amount}",
  niveauAnfaenger: "Beginner",
  niveauFortgeschritten: "Intermediate",
  niveauExperte: "Advanced",
  labelCompany: "Company",
  labelPhone: "Phone",
  labelLanguage: "Language",
  labelCrmSource: "CRM source",
  guestCrmSourceLabelExtended: "CRM source (e.g. website, referral)",
  guestListTitleSuffix: " list",
  guestListNewButton: "+ New",
  guestListPhoneAbbrev: "Tel.",
  guestListLastBookingPrefix: "Last",
  guestListEmptyTemplate: "No {clients} — adjust search or create new.",
  guestActivityHeading: "Activity & contacts",
  guestContactNewEntryLabel: "New entry",
  placeholderGuestContactBody: "Call note, follow-up, internal note…",
  guestContactKindNote: "Note",
  guestContactKindCall: "Call",
  guestContactKindEmail: "Email",
  guestContactKindMeeting: "Meeting",
  guestContactSaveButton: "Save entry",
  guestContactSavedToast: "Contact entry saved.",
  guestNoBookingsYetTemplate: "No {bookings} yet.",
  guestNewAppointmentCalendarTemplate: "New {appointment} (calendar)",
  guestOpenInvoicesAdj: "open",
  invoicePdfDescription: "Description",
  invoicePdfAmountChf: "Amount CHF",
  invoicePdfNet: "Net",
  invoicePdfTotalChf: "Total CHF",
  invoicePdfPaymentInfo: "Payment details",
  invoicePdfIbanPrefix: "IBAN:",
  loginMetadataTitleTemplate: "Sign in · {siteName}",
  loginMetadataDescriptionTemplate: "{teamLoginHome} via magic link",
  loginTitle: "Sign in",
  loginLeadMagicLink:
    "Magic link by email. After clicking the link in your inbox you are signed in.",
  loginDevNoticeStrong: "Without outbound email (Resend):",
  loginDevNoticeBeforeCmd: "an admin can on the server run",
  loginDevNoticeAfterCmd:
    " (container) to create a one-time link — see README.",
  loginErrorConfiguration:
    "Server configuration incomplete (e.g. RESEND_API_KEY or AUTH_SECRET).",
  loginErrorAccessDenied: "Access denied — this account is deactivated.",
  loginErrorGenericTemplate: "Error: {error}",
  loginEmailPlaceholder: "you@example.com",
  loginButtonSendLink: "Send link",
  loginButtonSending: "Sending…",
  loginMessageSignInFailed:
    "Sign-in failed. Check your email or try again later.",
  loginMessageLinkSent: "Link sent — please check your inbox.",
  loginFallbackLoading: "Loading…",
  loginLinkToHome: "Back to home",
  calendarPickAppointmentHintTemplate: "Select an {appointment} in the calendar…",
  guestPageSelectClientHintTemplate: "Select a {client}…",
  bookingModalInvalidSlot: "Invalid time slot.",
  bookingModalPickClientOrNewTemplate: "Please select or create a {client}.",
  bookingModalPickCourseTypeTemplate: "Select a {courseType}.",
  bookingModalGuestCreateFailedTemplate: "Could not create {client}.",
  bookingModalNewAppointmentTitleTemplate: "New {appointment}",
  bookingModalQuickGuestMinCharsTemplate:
    "At least 2 characters for a new {client}.",
  bookingModalClientSelectedTemplate: "{client} selected.",
  bookingModalQuickCreateGuestTemplate:
    "Create new {client} with entered name",
  bookingModalPriceChfOptionalLabel: "Price (CHF, optional)",
  bookingModalCourseTypeOptionTemplate:
    "{name} ({durationMin} min, CHF {priceCHF})",
  bookingModalCourseTypesLoadFailed:
    "Could not load course types. Please open the dialog again later.",
  bookingModalGuestSearchFailed: "Guest search failed — please try again.",
  bookingModalGuestPrefetchFailed: "Could not load the selected guest.",
  guestCreateModalTitleTemplate: "New {clientSingular}",
  guestCreatedToastTemplate: "{clientSingular} created.",
  bookingCreatedToastTemplate: "{appointmentSingular} created.",
  adminCourseTypeRowSummaryTemplate:
    "{name} · {durationMin} min · CHF {priceCHF}",
  bookingConfirmDeleteTemplate: "Really delete this {appointment}?",
  invoiceCreatedAlertTemplate:
    "{invoice} created — see {navInvoices} for PDF.",
  invoiceCreateButtonTemplate: "Create {invoice}",
  guestConfirmDeletePermanentTemplate: "Permanently delete {client}?",
  publicWizardPickServiceTypeTemplate: "Choose {serviceType}",
  publicWizardSubmitMissingTemplate:
    "Please select {service}, date and time.",
  publicWizardCoursesLoadFailed: "Could not load services.",
  publicWizardAvailabilityLoadFailed: "Could not load availability.",
  publicWizardSlotsLoadFailed: "Could not load time slots.",
  placeholderCrmSourceExample: "e.g. website, referral",
  guestPlaceholderLanguage: "en",
  privacyMusterDisclaimer:
    "Sample privacy notice for guidance only — not legal advice. Adapt all details to your organisation and have the text reviewed if needed.",
  privacySection1Title: "1. Data controller",
  privacySection1BodyTemplate:
    "Controller for processing in connection with this website:\n\n{siteName}\n{postalAddress}\n{siteDomain}\nEmail: {supportEmail}\n\nReference location: {issuerLocation}",
  privacySection2Title: "2. Purposes of processing",
  privacySection2BodyTemplate:
    "We process personal data to handle {bookingRequestPlural} and {bookingPlural}, for internal planning ({appointmentPlural}, {clientPlural}), for the protected team area (email magic-link sign-in), for {invoicePlural}, and to meet legal obligations.",
  privacySection3Title: "3. Legal bases",
  privacySection3BodyTemplate:
    "Contract or pre-contract measures (Art. 6(1)(b) GDPR) where you request services. Legitimate interests in secure operation of the site and team area (Art. 6(1)(f) GDPR). Legal obligations, e.g. retention (Art. 6(1)(c) GDPR). Consent where required (Art. 6(1)(a) GDPR).",
  privacySection4Title: "4. Categories of data",
  privacySection4BodyTemplate:
    "Contact and master data (e.g. name, email, phone), booking and appointment data, notes in the {clientPlural} area, team chat content, technical data (e.g. IP address, timestamps in server and audit logs).",
  privacySection5Title: "5. Retention",
  privacySection5BodyTemplate:
    "We delete data when the purpose ends, unless statutory retention (e.g. commercial or tax law) requires longer storage.",
  privacySection6Title: "6. Recipients and processors",
  privacySection6BodyTemplate:
    "Hosting of the application and database with your chosen provider. Transactional email (e.g. magic links, notifications) via an email provider (e.g. Resend). Optional bot protection (e.g. Cloudflare Turnstile) on the public booking form. Use Art. 28 GDPR processing agreements with processors where required.",
  privacySection7Title: "7. Your rights",
  privacySection7BodyTemplate:
    "Where applicable, you have rights of access, rectification, erasure, restriction, data portability and objection. You may lodge a complaint with a supervisory authority. Contact: {supportEmail}.",
  privacyContactPromptTemplate: "Privacy enquiries:",
  privacyHostingNoteBeforeLink: "Note: hosting and/or support may be via ",
  privacyHostingNoteAfterLink: ".",
  imprintMusterDisclaimer:
    "Sample legal notice — not legal advice. Add all mandatory details for your entity and jurisdiction.",
  imprintSection1Title: "Provider identification",
  imprintSection1BodyTemplate:
    "Provider of this website:\n\n{siteName}\n{postalAddress}\n{siteDomain}\nEmail: {supportEmail}",
  imprintSection2Title: "Representation / register",
  imprintSection2BodyTemplate:
    "Add in your fork (have it legally reviewed):\n\n• Names of authorised representatives (e.g. managing directors, board)\n• Legal form and registered office\n• Register type and number if applicable (e.g. commercial register, association register)\n• Register court\n\nRemove points that do not apply.",
  imprintSection3Title: "VAT",
  imprintSection3BodyTemplate:
    "VAT identification number pursuant to § 27a UStG (if applicable): _______________________________\n\nIf you do not display a VAT ID or are not subject to VAT: adjust or remove this section (legal review).",
  imprintSection4Title: "Responsible for content",
  imprintSection4BodyTemplate:
    "Requirements vary by medium and country. Typically: name and postal address of the person responsible for editorial content.\n\nAdd in your fork, e.g.: [first and last name], [street no., postcode city, country].",
  imprintSection5Title: "Online dispute resolution",
  imprintSection5BodyTemplate:
    "The European Commission provides a platform for online dispute resolution: https://ec.europa.eu/consumers/odr. We are not obliged and not willing to participate in consumer ADR proceedings — adjust if that applies to you.",
  publicFooterLegalPrefix: "Note:",
  chatComposerPlaceholder:
    "Message… (Enter to send, Shift+Enter for newline)",
  chatSendButton: "Send",
  chatEmptyConversationHint: "No messages in this conversation yet.",
  chatChannelNotFound: "Channel not found",
  chatDmNotAvailable: "Conversation not available",
  chatDmSelfForbidden: "You cannot message yourself",
  chatRecipientUnavailable: "Recipient unavailable",
  labelName: "Name",
  labelEmail: "Email",
  labelSearch: "Search",
  adminCourseCreateButton: "Create",
  adminCoursePublicPortalLabel: "Public (portal)",
  emailMagicLinkHeadingTemplate: "Sign in at {host}",
  emailMagicLinkButton: "Sign in",
  emailMagicLinkDisclaimer:
    "If you did not request this email, you can ignore it.",
  emailMagicLinkTextIntroTemplate: "Sign in at {host}",

  apiChatChannelOrRecipientRequired: "channelId or recipientId is required",
  apiChatEmptyMessage: "Empty message",
  apiAdminTeacherIdMissing: "teacherId is missing",
  apiConfirmBookingFkViolation:
    "The booking could not be created (data no longer matches). Please reload, pick the instructor again, and retry.",
  apiConfirmTeacherNotAssignable:
    "The selected instructor is not active or not allowed. Refresh the teacher list and choose again.",
  apiAdminCourseTypeDeleteBlockedTemplate:
    "{serviceTypeSingular} is still linked to {bookingPlural} or {bookingRequestPlural} and cannot be deleted.",
  adminCoursePlaceholderName: "Name",
  adminCoursePlaceholderDurationMin: "Duration (min)",
  adminCoursePlaceholderPriceChf: "Price CHF",
  adminCoursePlaceholderMaxParticipants: "Max participants",
  chatMessageTooLongTemplate: "Message too long (max. {max} characters)",
  chatChannelCreateFailed: "Could not create channel",
  chatMessageSendFailed: "Could not send message",
  apiChatChannelNameTooShort: "Name too short",
  invoiceTableCurrency: "CHF",
  apiInvalidData: "Invalid data",
  apiInvalidEmail: "Invalid email",
  apiInviteFailed: "Invitation failed",
  apiResendInviteFailed: "Could not resend",
  apiPatchNoFields: "No fields",
  apiNothingToUpdate: "Nothing to update",
  apiBookingListDateRangeRequired:
    "dateFrom and dateTo (YYYY-MM-DD) are required",
  apiAdminInviteRateLimited: "Too many invitations. Please try again later.",
  apiAdminSelfDeactivateForbidden: "You cannot deactivate yourself",
  apiTurnstileFailed: "Security check failed",
  apiPublicSlotsParamsRequired:
    "courseTypeId and date (YYYY-MM-DD) are required",
  apiPublicAvailabilityParamsRequired:
    "courseTypeId and month (YYYY-MM) are required",
  apiAdminUserNotFound: "User not found",
  apiAdminUserExists:
    "User already exists. To resend a magic link, use “Resend link” in the table.",
  apiDbSchemaColumnDrift:
    "Database schema is out of date. Run migrations on the server (npm run db:migrate:apply in the app container).",
  apiDbSchemaRelationDriftTemplate:
    "Database schema is out of date. Run migrations (e.g. 0001_rate_limit_audit for {navAuditLog}).",
  apiTechnicalErrorGeneric: "A technical error occurred.",
  apiGuestContactSaveFailed: "Could not save contact entry",
  msgTimeSlotUnavailableForStaff:
    "Time slot not available for this {staffPlural}",
  msgInvalidServiceType: "Invalid {serviceTypeSingular}",
  msgCourseDurationInvalid:
    "Invalid course duration — check the service type in admin settings.",
  msgStaffUnavailableAtSlot: "{staffPlural} not available at this time",
  msgBookingRequestNoLongerOpen: "{bookingRequest} is no longer open",
  msgBookingInsertFailed: "{booking} failed",
  msgBookingRequestInsertFailed: "{bookingRequest} failed",
  msgInvoiceInsertFailed: "Could not create {invoice}",
  msgInvoiceAlreadyForBooking:
    "An {invoice} already exists for this {booking}",
  msgGuestHasBookingsNoDelete:
    "{client} has {bookings} and cannot be deleted",
  msgEntityNotFound: "{entity} not found",
  configInviteOriginMissing:
    "AUTH_URL, NEXTAUTH_URL or NEXT_PUBLIC_APP_URL must be set for invitation emails.",
  configAuthSecretMissing: "AUTH_SECRET / NEXTAUTH_SECRET is missing.",
  apiUserByEmailNotFound: "No user with this email",
  apiUserDeactivatedReactivateFirst:
    "User is deactivated — reactivate first",
  authSignInRateLimitIp:
    "Too many sign-in attempts from this network. Please try again later.",
  authSignInRateLimitEmail:
    "Too many sign-in attempts for this email. Please try again later.",
  adminDashboardLoading: "Loading dashboard…",
  adminTabStaffUsersTemplate: "{staffCollectivePlural} & users",
  adminMetricBookingsMonthLabelTemplate: "{bookingPlural} (month)",
  adminMetricBookingsMonthSub: "In the current calendar month",
  adminMetricRevenueLabel: "Revenue",
  adminMetricRevenueSub:
    "Sum of prices (excluding cancelled), current month",
  adminMetricActiveStaffLabelTemplate: "Active {staffCollectivePlural}",
  adminMetricGuestsTotalLabelTemplate: "{clientPlural} total",
  adminChartBookingsByMonthTitleTemplate:
    "{bookingPlural} per month ({year})",
  adminChartRevenueByStaffTitleTemplate:
    "Revenue per {staffCollectivePlural} (month)",
  adminChartRevenueByStaffHint:
    "Bars are relative to the highest revenue in the list",
  adminStatsTableHeaderChf: "CHF",
  adminUserListLoading: "Loading user list…",
  adminInviteEmailPlaceholder: "Email to invite",
  uiErrorHttpTemplate: "Error ({status})",
  adminSendMagicLink: "Send magic link",
  adminUsersEmptyHint:
    "No users yet. Enter an email above and send a magic link.",
  adminMagicLinkResentToast: "Magic link was sent again.",
  adminResendMagicLink: "Resend link",
  adminActivateUser: "Activate",
  adminActivateUserFailed: "Could not activate",
  adminCannotChangeOwnRoleHere: "You cannot change your own role here",
  adminRoleChangeFailed: "Could not change role",
  adminRoleToggle: "Toggle role",
  adminConfirmDeactivateUserTemplate:
    "Really deactivate {email}? They will no longer be able to sign in.",
  adminDeactivateUserFailed: "Could not deactivate",
  adminDeactivateUser: "Deactivate",
  labelRole: "Role",
  labelActive: "Active",
  uiYes: "yes",
  uiNo: "no",
  uiEmDash: "—",
  tableColAction: "Action",
  auditLogServerError: "Server error while loading the log.",
  auditLogHttpErrorTemplate: "HTTP {status}",
  auditLogLoadFailedPrefix: "Could not load log:",
  auditColTimeUtc: "Time (UTC)",
  auditColAction: "Action",
  auditColActor: "Actor",
  auditColResource: "Resource",
  auditColIp: "IP",
  auditColDetails: "Details",
  publicBookingCourseMetaTemplate:
    "{durationMin} min · max. {maxParticipants} · CHF {priceCHF}",
  invoicePdfVatTemplate: "VAT {percent}%",
  configResendApiKeyMissing:
    "RESEND_API_KEY is missing — magic link cannot be sent.",
  emailBookingRequestSubjectTemplate:
    "We received your {bookingRequest} — {siteName}",
  emailBookingRequestBodyLineTemplate:
    "Thank you for your {serviceSingular} request. We usually respond within 24 hours.",
  emailSignoffWithSiteTemplate: "Kind regards<br/>{siteName}",
  emailAdminNewRequestSubjectTemplate: "New {bookingRequest}: {guestName}",
  emailAdminNewRequestIntroTemplate: "New {bookingRequest} in the portal.",
  emailAdminNewRequestDateTimeLabel: "Date/time:",
  emailCtaOpenAdmin: "Open in admin",
  emailInviteSubjectTemplate: "Invitation to {siteName} — sign in",
  emailInviteGreetingTemplate: "Hello {name},",
  emailInviteBodyIntroTemplate:
    "You have been invited as {staffRole} for {siteName}. Use the link below to sign in (one-time use, approx. 24&nbsp;hours):",
  emailInviteCtaSignInTemplate: "Sign in to {siteName}",
  emailInviteLoginFallbackLineTemplate:
    "If the link expires, request a new magic link on the <a href=\"{loginUrl}\">sign-in page</a> using the same email address.",
  emailBookingConfirmedSubjectTemplate:
    "Your {serviceSingular} is confirmed — {siteName}",
  emailBookingConfirmedIntroTemplate: "Your {bookingSingular} is confirmed:",
  emailBookingConfirmedClosing: "We look forward to seeing you!",
} as const;

/** Team-channel demo lines for `npm run db:seed` when `NEXT_PUBLIC_HTML_LANG=en` */
export const DEMO_TEAM_CHANNEL_SEED_MESSAGES_EN = [
  "Welcome to the team channel!",
  "Please keep appointments up to date in the calendar.",
  "Questions? Contact an admin.",
  "Have a great weekend!",
  "Reminder: review booking requests in Admin.",
] as const;
