/**
 * Englische UI-Texte bei `NEXT_PUBLIC_HTML_LANG=en`.
 * Fehlende Keys bleiben bei den deutschen `FORK_DEFAULTS.labels`.
 */
export const BRAND_LABELS_EN = {
  staffSingular: "Instructor",
  staffPlural: "Instructors",
  staffCollectivePlural: "Instructors",
  staffRoleInInvite: "instructor",
  clientSingular: "Guest",
  clientPlural: "Guests",
  serviceSingular: "Course",
  servicePlural: "Courses",
  bookingSingular: "Booking",
  bookingPlural: "Bookings",
  serviceTypeSingular: "Course type",
  serviceTypePlural: "Course types",
  requestServiceCta: "Request a course",
  teamLoginNav: "Login (team)",
  teamLoginHome: "Team login",
  teamAreaTitle: "Team area",
  appointmentSingular: "Appointment",
  appointmentPlural: "Appointments",
  bookingRequestSingular: "Booking request",
  bookingRequestPlural: "Booking requests",
  requestSingular: "Request",
  requestPlural: "Requests",
  invoiceSingular: "Invoice",
  invoicePlural: "Invoices",
  navCalendar: "Calendar",
  navInvoices: "Invoices",
  navMonthlyHoursReport: "Hours report",
  navChat: "Chat",
  navAdmin: "Admin",
  navAudit: "Audit",
  navAuditLog: "Audit log",
  navTeam: "Team",
  navSignOut: "Sign out",
  navSessionLoadingEllipsis: "…",
  navHome: "Home",
  navContact: "Contact",
  navPrivacy: "Privacy",
  navImpressum: "Legal notice",
  navSkipToContent: "Skip to main content",
  publicMainNavAria: "Main navigation",
  navGuestAppointments: "My appointments",
  navDashboard: "Dashboard",
  clientSkillFilterLabel: "Level",
  chatPageIntroSegment1Template:
    "{navTeam} channels and direct messages. While ",
  chatPageIntroSegment2Template: " is running, the header shows ",
  chatPageIntroSegment3Template: "; otherwise it uses ",
  chatChannelsHeading: "Channels",
  chatDirectHeading: "Direct",
  chatConnectionLive: "Live (Socket.io)",
  chatConnectionPolling: "Polling",
  calNext: "Next",
  calPrevious: "Back",
  calToday: "Today",
  calMonth: "Month",
  calWeek: "Week",
  calDay: "Day",
  calAgenda: "Agenda",
  calDate: "Date",
  calTime: "Time",
  calShowMoreSuffix: "more",
  statusGeplant: "Scheduled",
  statusDurchgefuehrt: "Completed",
  statusStorniert: "Cancelled",
  statusOffen: "Open",
  statusBezahlt: "Paid",
  statusAnfrageNeu: "New",
  statusAnfrageBestaetigt: "Confirmed",
  statusAnfrageAbgelehnt: "Declined",
  uiErrorGeneric: "Error",
  uiSave: "Save",
  uiSaveInProgress: "Saving…",
  uiSaveFailed: "Could not save",
  uiDeleteFailed: "Could not delete",
  uiStatusUpdateFailed: "Could not update status",
  uiNameRequired: "Name is required",
  uiValidationNameAndEmail: "Name and a valid email are required.",
  placeholderClientSearch: "Name or email…",
  placeholderClientSearchModal: "Search name or email…",
  placeholderEmail: "Email",
  placeholderPhoneOptional: "Phone (optional)",
  uiCancel: "Cancel",
  uiEdit: "Edit",
  uiClose: "Close",
  internalMobileMenuOpen: "Menu",
  toastSuccessOn: "Success toasts: on",
  toastSuccessOff: "Success toasts: off",
  toastInfoOn: "Info toasts: on",
  toastInfoOff: "Info toasts: off",
  toastSessionQuietOn: "Session quiet: on",
  toastSessionQuietOff: "Session quiet: off",
  toastSessionQuietBadge: "Session quiet active",
  uiRefresh: "Refresh",
  uiDelete: "Delete",
  uiContactTextRequired: "Text is required",
  fieldPrice: "Price",
  fieldStatus: "Status",
  fieldSource: "Source",
  fieldNotes: "Notes",
  fieldPaymentStatus: "Payment",
  fieldPaymentExternalRef: "Payment reference",
  bookingPaymentLabelNone: "Not recorded",
  bookingPaymentLabelDeposit: "Deposit",
  bookingPaymentLabelPaid: "Paid",
  bookingPaymentLabelRefunded: "Refunded",
  bookingActionStornieren: "Cancel booking",
  uiFilterAll: "All",
  invoiceStatsLoading: "Loading monthly stats…",
  invoiceMetricOpenMonth: "Open (month)",
  invoiceMetricPaidMonth: "Paid (month)",
  invoiceTableNumberAbbrev: "No.",
  invoiceTableDate: "Date",
  invoiceTableActions: "Actions",
  invoicePreview: "Preview",
  invoicePdfLink: "PDF",
  invoiceDownloadPdf: "Download PDF",
  invoiceMarkPaidButton: "Mark as paid",
  invoiceMarkedPaidToastTemplate: "{invoice} marked as paid.",
  apiUnauthorized: "Not signed in.",
  apiForbidden: "Permission denied.",
  apiNotFound: "Not found",
  apiValidationDefault: "Invalid input",
  apiTooManyRequests: "Too many requests. Please try again later.",
  apiMaintenanceMode:
    "The booking portal is temporarily unavailable. Please try again later.",
  adminRequestConfirm: "Confirm",
  adminRequestReject: "Decline",
  adminRequestConfirmedToastTemplate:
    "{bookingRequestSingular} confirmed and {bookingSingular} created.",
  adminRequestRejectedToastTemplate:
    "{bookingRequestSingular} declined.",
  adminBookingRequestAssignStaffTitleTemplate: "Assign {staffCollectivePlural}",
  adminBookingRequestConfirmCreateTemplate: "Create {bookingSingular}",
  adminBookingRequestRejectTitleTemplate: "Decline {bookingRequestSingular}",
  adminNoTeachersForRequestConfirmHint:
    "No active teacher or admin loaded. Under Admin → Users, invite or activate at least one teacher.",
  adminSelectStaffPlaceholder: "— Select person —",
  adminNewRequestToastTitleTemplate: "New {bookingRequest}",
  adminNewRequestToastBodyTemplate:
    "At least one new {requestSingular} has arrived.",
  adminNewRequestToastCtaTemplate: "Go to {requestPlural}",
  placeholderRejectReasonOptional: "Reason (optional)",
  auditLogUnauthorized: "Not signed in — please sign in again.",
  auditLogForbiddenTemplate: "No permission for {navAuditLog}.",
  uiLoadingEllipsis: "Loading…",
  uiNoEntriesYet: "No entries yet.",
  navPageLoadingTemplate: "Loading {navTitle}…",
  staffCollectiveListLoadingTemplate:
    "Loading {staffCollectivePlural} list…",
  staffListEmptyTemplate:
    "No {staffPlural} found. Invite {staffCollectivePlural} via {navAdmin} or check the database.",
  teacherLegendEmptyTemplate: "No active {staffPlural} loaded.",
  adminCourseTypesLoadingTemplate: "Loading {serviceTypePlural}…",
  adminCourseTypesEmptyTemplate:
    "No {serviceTypePlural} yet. Create one above or run seed/migrations.",
  adminCourseTypeCreateFailedTemplate:
    "Could not create {serviceTypeSingular}",
  calendarFilterShowAllStaffTemplate: "Show all {staffCollectivePlural}",
  calendarFilterTeacherByTemplate: "Filter {staffSingular}",
  publicWizardPickDate: "Pick a date",
  publicWizardTimeAndContact: "Time & contact",
  publicWizardSlotsTitle: "Time slots",
  publicAvailFree: "Free",
  publicAvailPartial: "Partial",
  publicAvailFull: "Full",
  publicCalNotSelectable: "Not selectable",
  publicApproxEndShort: "Ends approx.",
  calWeekdayMo: "Mon",
  calWeekdayDi: "Tue",
  calWeekdayMi: "Wed",
  calWeekdayDo: "Thu",
  calWeekdayFr: "Fri",
  calWeekdaySa: "Sat",
  calWeekdaySo: "Sun",
  calMonthPrevAria: "Previous month",
  calMonthNextAria: "Next month",
  bookingWizardStepperAria: "Booking steps",
  bookingWizardStepStatusTemplate: "Step {current} of {total}",
  publicWizardCoursePickGroupAria: "Choose course type",
  publicWizardNiveauGroupAria: "Choose level",
  placeholderFirstName: "First name",
  placeholderLastName: "Last name",
  placeholderMessageOptional: "Message (optional)",
  publicTurnstileLabel: "Security check",
  publicSummaryDateLabel: "Date",
  publicSummaryPriceLabel: "Price",
  publicNoPaymentDisclaimer:
    "No payment now — we confirm by email within 24 hours.",
  publicPortalPoliciesHeading: "Cancellation and payment",
  publicPortalPoliciesCancellationLead:
    "Cancel via “My appointments” while the session is still scheduled and not yet completed.",
  publicPortalPoliciesCancellationDeadlineTemplate:
    "Online cancellation is possible until {hours} hours before the agreed start time.",
  publicPortalPoliciesPayment:
    "There is no prepayment in this portal. After confirmation you will receive an invoice; payment terms and bank details are on the invoice or in your confirmation email.",
  maintenancePageBadge: "Status",
  maintenancePageTitle: "Booking portal under maintenance",
  maintenancePageMetaDescription:
    "The public booking portal is temporarily unavailable.",
  maintenancePageBody:
    "We are performing maintenance or the portal is briefly limited. Please try again later or email us.",
  maintenancePageMagicLinkHint:
    "If you opened an access link from an email: please use the same link again after maintenance (the address bar link is not kept during maintenance).",
  homeMaintenanceBannerText:
    "Note: The booking portal is temporarily under maintenance.",
  homeMaintenanceBannerCta: "Maintenance details",
  publicThanksTitleTemplate: "Thank you, {name}!",
  publicThanksIntroTemplate:
    "Your {request} was received. You will get a confirmation shortly at",
  publicReferenceLabel: "Reference",
  publicWizardSubmitRequestCtaTemplate: "Send {requestSingular} →",
  publicWizardNewRequestAgainTemplate: "Submit another {requestSingular}",
  guestBookingListPriceTemplate: "{currency} {amount}",
  niveauAnfaenger: "Beginner",
  niveauFortgeschritten: "Intermediate",
  niveauExperte: "Advanced",
  labelCompany: "Company",
  labelPhone: "Phone",
  labelLanguage: "Language",
  labelCrmSource: "CRM source",
  guestCrmSourceLabelExtended: "CRM source (e.g. website, referral)",
  guestListTitleSuffix: " list",
  guestListNewButton: "+ New",
  guestListPhoneAbbrev: "Tel.",
  guestListLastBookingPrefix: "Last",
  guestListEmptyTemplate: "No {clients} — adjust search or create new.",
  guestActivityHeading: "Activity & contacts",
  guestContactNewEntryLabel: "New entry",
  placeholderGuestContactBody: "Call note, follow-up, internal note…",
  guestContactKindNote: "Note",
  guestContactKindCall: "Call",
  guestContactKindEmail: "Email",
  guestContactKindMeeting: "Meeting",
  guestContactSaveButton: "Save entry",
  guestContactSavedToast: "Contact entry saved.",
  guestNoBookingsYetTemplate: "No {bookings} yet.",
  guestNewAppointmentCalendarTemplate: "New {appointment} (calendar)",
  guestOpenInvoicesAdj: "open",
  invoicePdfDescription: "Description",
  invoicePdfAmountChf: "Amount CHF",
  invoicePdfNet: "Net",
  invoicePdfTotalChf: "Total CHF",
  invoicePdfPaymentInfo: "Payment details",
  invoicePdfIbanPrefix: "IBAN:",
  loginMetadataTitleTemplate: "Sign in · {siteName}",
  loginMetadataDescriptionTemplate: "{teamLoginHome} via magic link",
  loginTitle: "Sign in",
  loginLeadMagicLink:
    "Magic link by email. After clicking the link in your inbox you are signed in.",
  loginDevNoticeStrong: "Without outbound email (Resend):",
  loginDevNoticeBeforeCmd: "an admin can on the server run",
  loginDevNoticeAfterCmd:
    " (container) to create a one-time link — see README.",
  loginErrorConfiguration:
    "Server configuration incomplete (e.g. RESEND_API_KEY or AUTH_SECRET).",
  loginErrorAccessDenied: "Access denied — this account is deactivated.",
  loginErrorGenericTemplate: "Error: {error}",
  loginEmailPlaceholder: "you@example.com",
  loginButtonSendLink: "Send link",
  loginButtonSending: "Sending…",
  loginMessageSignInFailed:
    "Sign-in failed. Check your email or try again later.",
  loginMessageLinkSent: "Link sent — please check your inbox.",
  loginFallbackLoading: "Loading…",
  loginLinkToHome: "Back to home",
  calendarPickAppointmentHintTemplate: "Select an {appointment} in the calendar…",
  guestPageSelectClientHintTemplate: "Select a {client}…",
  bookingModalInvalidSlot: "Invalid time slot.",
  bookingModalPickClientOrNewTemplate: "Please select or create a {client}.",
  bookingModalPickCourseTypeTemplate: "Select a {courseType}.",
  bookingModalGuestCreateFailedTemplate: "Could not create {client}.",
  bookingModalNewAppointmentTitleTemplate: "New {appointment}",
  bookingModalQuickGuestMinCharsTemplate:
    "At least 2 characters for a new {client}.",
  bookingModalClientSelectedTemplate: "{client} selected.",
  bookingModalQuickCreateGuestTemplate:
    "Create new {client} with entered name",
  bookingModalPriceChfOptionalLabel: "Price (CHF, optional)",
  bookingModalCourseTypeOptionTemplate:
    "{name} ({durationMin} min, CHF {priceCHF})",
  bookingModalCourseTypesLoadFailed:
    "Could not load course types. Please open the dialog again later.",
  bookingModalGuestSearchFailed: "Guest search failed — please try again.",
  bookingModalGuestPrefetchFailed: "Could not load the selected guest.",
  guestCreateModalTitleTemplate: "New {clientSingular}",
  guestCreatedToastTemplate: "{clientSingular} created.",
  bookingCreatedToastTemplate: "{appointmentSingular} created.",
  adminCourseTypeRowSummaryTemplate:
    "{name} · {durationMin} min · CHF {priceCHF}",
  bookingConfirmDeleteTemplate: "Really delete this {appointment}?",
  invoiceCreatedAlertTemplate:
    "{invoice} created — see {navInvoices} for PDF.",
  invoiceCreateButtonTemplate: "Create {invoice}",
  guestConfirmDeletePermanentTemplate: "Permanently delete {client}?",
  publicWizardPickServiceTypeTemplate: "Choose {serviceType}",
  publicWizardSubmitMissingTemplate:
    "Please select {service}, date and time.",
  publicWizardCoursesLoadFailed: "Could not load services.",
  publicWizardAvailabilityLoadFailed: "Could not load availability.",
  publicWizardSlotsLoadFailed: "Could not load time slots.",
  placeholderCrmSourceExample: "e.g. website, referral",
  guestPlaceholderLanguage: "en",
  legalTestProjectNotice:
    "Note: This application ({siteDomain}) is a test and demonstration project by MMIND (mmind.ai). There is no claim to completeness, availability or production operation; demo data may be deleted at any time.",
  privacyMusterDisclaimer:
    "This page does not contain a full privacy policy. The binding information is published by MMIND at https://mmind.ai/datenschutz — including controller, legal bases and your rights.",
  privacySection1Title: "1. References instead of a full statement",
  privacySection1BodyTemplate:
    "This instance ({siteName}, {siteDomain}) is for demonstration purposes only in the context of mmind.ai.\n\nController and full privacy policy:\nMMIND GmbH — https://mmind.ai/datenschutz\n\nPrivacy contact: info@mmind.ai (subject: “Privacy”).\n\nMMIND address (excerpt):\n{postalAddress}",
  privacySection2Title: "2. What data may this demo process?",
  privacySection2BodyTemplate:
    "The booking and team demo may involve e.g. contact data, {bookingRequestPlural}, {bookingPlural}, {appointmentPlural}, {clientPlural} notes, chat content and technical logs (e.g. IP, timestamps) — only as needed for the demo. Details and retention: see https://mmind.ai/datenschutz",
  privacyContactPromptTemplate: "Privacy enquiries (MMIND):",
  privacyHostingNoteBeforeLink: "Organisation and hosting information: ",
  privacyHostingNoteAfterLink:
    " — full details only on MMIND’s website; this subdomain is a test project.",
  imprintMusterDisclaimer:
    "No full imprint for this subdomain: legal provider information and disclaimers for MMIND GmbH are at https://mmind.ai/impressum . This application is a non-production test project.",
  imprintSection1Title: "1. Responsible party / full imprint",
  imprintSection1BodyTemplate:
    "This site ({siteDomain}, project “{siteName}”) is a test project by MMIND.\n\nFull imprint and legal notice:\nhttps://mmind.ai/impressum\n\nMMIND GmbH (excerpt from mmind.ai):\n{postalAddress}\n\nGeneral contact: info@mmind.ai",
  imprintSection2Title: "2. Liability and disclaimer",
  imprintSection2BodyTemplate:
    "For liability, copyright and further legal notices, the version at https://mmind.ai/impressum applies.\n\nThis demo is not a commercial service; content and features may be incomplete or faulty.",
  publicFooterLegalPrefix: "Note:",
  publicFooterTestProjectLine:
    "mmind.ai test project — https://mmind.ai · Not a production service.",
  loginTestProjectBrief:
    "mmind.ai test project (https://mmind.ai) — not a production ski school.",
  chatComposerPlaceholder:
    "Message… (Enter to send, Shift+Enter for newline)",
  chatSendButton: "Send",
  chatEmptyConversationHint: "No messages in this conversation yet.",
  chatChannelNotFound: "Channel not found",
  chatDmNotAvailable: "Conversation not available",
  chatDmSelfForbidden: "You cannot message yourself",
  chatRecipientUnavailable: "Recipient unavailable",
  labelName: "Name",
  labelEmail: "Email",
  labelSearch: "Search",
  adminCourseCreateButton: "Create",
  adminCoursePublicPortalLabel: "Public (portal)",
  emailMagicLinkHeadingTemplate: "Sign in at {host}",
  emailMagicLinkButton: "Sign in",
  emailMagicLinkDisclaimer:
    "If you did not request this email, you can ignore it.",
  emailMagicLinkTextIntroTemplate: "Sign in at {host}",

  apiChatChannelOrRecipientRequired: "channelId or recipientId is required",
  apiChatEmptyMessage: "Empty message",
  apiAdminTeacherIdMissing: "teacherId is missing",
  apiConfirmBookingFkViolation:
    "The booking could not be created (data no longer matches). Please reload, pick the instructor again, and retry.",
  apiConfirmTeacherNotAssignable:
    "The selected instructor is not active or not allowed. Refresh the teacher list and choose again.",
  apiAdminCourseTypeDeleteBlockedTemplate:
    "{serviceTypeSingular} is still linked to {bookingPlural} or {bookingRequestPlural} and cannot be deleted.",
  adminCoursePlaceholderName: "Name",
  adminCoursePlaceholderDurationMin: "Duration (min)",
  adminCoursePlaceholderPriceChf: "Price CHF",
  adminCoursePlaceholderMaxParticipants: "Max participants",
  chatMessageTooLongTemplate: "Message too long (max. {max} characters)",
  chatChannelCreateFailed: "Could not create channel",
  chatMessageSendFailed: "Could not send message",
  apiChatChannelNameTooShort: "Name too short",
  invoiceTableCurrency: "CHF",
  apiInvalidData: "Invalid data",
  apiInvalidEmail: "Invalid email",
  apiInviteFailed: "Invitation failed",
  apiResendInviteFailed: "Could not resend",
  apiPatchNoFields: "No fields",
  apiNothingToUpdate: "Nothing to update",
  apiBookingListDateRangeRequired:
    "dateFrom and dateTo (YYYY-MM-DD) are required",
  apiAdminInviteRateLimited: "Too many invitations. Please try again later.",
  apiAdminSelfDeactivateForbidden: "You cannot deactivate yourself",
  apiTurnstileFailed: "Security check failed",
  apiPublicSlotsParamsRequired:
    "courseTypeId and date (YYYY-MM-DD) are required",
  apiPublicAvailabilityParamsRequired:
    "courseTypeId and month (YYYY-MM) are required",
  apiAdminUserNotFound: "User not found",
  apiAdminUserExists:
    "User already exists. To resend a magic link, use “Resend link” in the table.",
  apiDbSchemaColumnDrift:
    "Database schema is out of date. Run migrations on the server (npm run db:migrate:apply in the app container).",
  apiDbSchemaRelationDriftTemplate:
    "Database schema is out of date. Run migrations (e.g. 0001_rate_limit_audit for {navAuditLog}).",
  apiTechnicalErrorGeneric: "A technical error occurred.",
  apiGuestContactSaveFailed: "Could not save contact entry",
  msgTimeSlotUnavailableForStaff:
    "Time slot not available for this {staffPlural}",
  msgInvalidServiceType: "Invalid {serviceTypeSingular}",
  msgCourseDurationInvalid:
    "Invalid course duration — check the service type in admin settings.",
  msgStaffUnavailableAtSlot: "{staffPlural} not available at this time",
  msgBookingRequestNoLongerOpen: "{bookingRequest} is no longer open",
  msgBookingInsertFailed: "{booking} failed",
  msgBookingRequestInsertFailed: "{bookingRequest} failed",
  msgInvoiceInsertFailed: "Could not create {invoice}",
  msgInvoiceAlreadyForBooking:
    "An {invoice} already exists for this {booking}",
  msgGuestHasBookingsNoDelete:
    "{client} has {bookings} and cannot be deleted",
  msgEntityNotFound: "{entity} not found",
  configInviteOriginMissing:
    "AUTH_URL, NEXTAUTH_URL or NEXT_PUBLIC_APP_URL must be set for invitation emails.",
  configAuthSecretMissing: "AUTH_SECRET / NEXTAUTH_SECRET is missing.",
  apiUserByEmailNotFound: "No user with this email",
  apiUserDeactivatedReactivateFirst:
    "User is deactivated — reactivate first",
  authSignInRateLimitIp:
    "Too many sign-in attempts from this network. Please try again later.",
  authSignInRateLimitEmail:
    "Too many sign-in attempts for this email. Please try again later.",
  adminDashboardLoading: "Loading dashboard…",
  adminTabStaffUsersTemplate: "{staffCollectivePlural} & users",
  adminTabWeeklyHours: "Availability",
  adminWeeklyHoursHelp:
    "With no rows, the booking portal’s default time grid (07:00–20:00) applies. Once you add rows, appointments must fall fully inside these weekly windows (in addition to blocks and existing bookings). Overnight windows are not supported.",
  adminWeeklyHoursStaffLabel: "Person:",
  adminWeeklyHoursAddRow: "Add row",
  adminWeeklyHoursRemoveRow: "Remove",
  adminWeeklyHoursSave: "Save",
  adminWeeklyHoursSavedToast: "Weekly hours saved.",
  adminWeeklyHoursSaveFailed: "Could not save weekly hours.",
  adminWeeklyHoursEmptyHint:
    "No weekly windows — the default portal grid applies. Add a row to set fixed working hours.",
  adminWeeklyHoursInvalidWindow: "End time must be after start time.",
  adminVacationSectionTitle: "Vacation / time off",
  adminVacationHelp:
    "Full days unavailable (e.g. vacation). No bookings can be made for this person in that range. The team calendar shows those days as a highlighted block.",
  adminVacationEmptyHint: "No vacation periods. Add a row to plan time off.",
  adminVacationAddRow: "Add date range",
  adminVacationRemoveRow: "Remove",
  adminVacationNotePlaceholder: "Note (optional)",
  adminVacationSave: "Save vacation",
  adminVacationSavedToast: "Vacation / time off saved.",
  adminVacationSaveFailed: "Could not save vacation periods.",
  adminVacationInvalidRange: "End date must be on or after start date.",
  adminVacationSpanTooLong: "A range may cover at most 370 days.",
  calendarScheduleLegendTitle: "Working hours & calendar legend",
  calendarScheduleWeeklyHoursLabel: "Regular windows:",
  calendarLegendAppointments:
    "Appointments: coloured blocks (same colours as staff badges above).",
  calendarLegendVacation: "Vacation / off",
  calendarLegendBlocked: "Blocked (part of day)",
  adminTabMonthlyReport: "Monthly hours",
  monthlyHoursReportTitle: "Monthly hours",
  monthlyHoursReportIntro:
    "Productive hours come from appointments (excluding cancelled). Add office, prep, meetings, etc. as manual entries with a category — similar to non-billable codes in many ERPs.",
  monthlyHoursProductive: "Productive (teaching)",
  monthlyHoursInternalTotal: "Internal / general",
  monthlyHoursTotalWorked: "Total worked",
  monthlyHoursBookingsDetail: "Appointments this month",
  monthlyHoursManualEntries: "Manual time entries",
  monthlyHoursAddEntry: "Save entry",
  monthlyHoursExportCsv: "Download CSV",
  monthlyHoursMonthLabel: "Month",
  monthlyHoursSelectStaff: "Person",
  monthlyHoursCancelledBookings: "Cancelled appointments (no hours)",
  monthlyHoursHoursAbbr: "h",
  monthlyHoursDate: "Date",
  monthlyHoursTime: "Time",
  monthlyHoursCourse: "Service",
  monthlyHoursGuest: "Guest",
  monthlyHoursDuration: "Duration",
  monthlyHoursCategory: "Category",
  monthlyHoursNote: "Note",
  monthlyHoursActions: "Action",
  monthlyHoursDelete: "Delete",
  monthlyHoursSavedToast: "Time entry saved.",
  monthlyHoursDeletedToast: "Entry deleted.",
  monthlyHoursLoadError: "Could not load report.",
  navPayroll: "Payroll",
  adminTabPayroll: "Payroll (LI)",
  payrollPageTitle: "Payroll (helper calculation)",
  payrollPageIntro:
    "Simplified monthly calculation based on the Principality of Liechtenstein government leaflet (part-time / low wages, 2026). Not legal or tax advice — statute and authorities prevail.",
  payrollMerkblattLinkLabel: "Payroll leaflet (PDF, government LI)",
  payrollLegalBullets:
    "AHV-IV-FAK: register as employer; contributions (EE 5.4 % / ER 7.885 % on insured earnings). Health care: employer reimburses employee share (adult CHF 180.50 / youth CHF 90.25 per month at 42 h/wk in the leaflet example). Withholding: 4 % if annual gross up to CHF 40,000 (leaflet section 7). Accident insurance, wage declaration, employment reporting at bm.llv.li, eLohn statements — see leaflet.",
  payrollProfileHeading: "Payroll master data (admin)",
  payrollHourlyGrossLabel: "Gross hourly wage — productive (CHF)",
  payrollHourlyInternalLabel: "Gross hourly — internal (CHF, empty = same as productive)",
  payrollEstimatedAnnualGrossLabel:
    "Estimated annual gross CHF (optional, for withholding instead of ×12/YTD)",
  payrollWhtBasisLabel: "Annual gross basis (tax)",
  payrollYtdBeforeMonth: "YTD finalized (prior months)",
  payrollWhtMethodManual: "manual estimate",
  payrollWhtMethodYtd: "finalized YTD + this month",
  payrollWhtMethodTimes12: "12 × monthly gross",
  payrollSnapshotBadge: "Month finalized",
  payrollSnapshotFinalized: "Finalized on {date} by {by}.",
  payrollFinalizeMonth: "Finalize month (snapshot)",
  payrollUnlockMonth: "Remove finalization",
  payrollSnapshotSavedToast: "Payroll month finalized.",
  payrollSnapshotDeletedToast: "Finalization removed.",
  payrollSnapshotNoComputation: "No calculation — check profile and hours.",
  payrollSnapshotNotFound: "No finalization for this month.",
  payrollExportCsv: "CSV year export (finalized)",
  accountingExportCsv: "CSV year export (bookings & invoices)",
  accountingExportHint:
    "DATEV-style columns for all bookings and invoices in the calendar year (map accounts with your accountant).",
  accountingExportYearLabel: "Export year",
  guestPortalPageTitle: "My appointments",
  guestPortalPageIntro:
    "Enter the same email you used to book — we send a secure link (valid 7 days).",
  guestPortalEmailLabel: "Email",
  guestPortalSendLink: "Send link",
  guestPortalLinkSent: "If there are matching appointments, a link has been sent.",
  guestPortalLogout: "Sign out / other email",
  guestPortalLoadFailed: "Could not load appointments.",
  guestPortalInvalidToken: "Invalid or expired access.",
  guestPortalRateLimited: "Too many requests. Please try again later.",
  guestPortalAlreadyCancelled: "This appointment is already cancelled.",
  guestPortalCancelTooLateTemplate:
    "Cancellation is only possible at least {hours} hours before the start.",
  guestPortalCancel: "Cancel",
  guestPortalInvoicePdf: "Invoice PDF",
  guestPortalColWhen: "Date / time",
  guestPortalColCourse: "Course",
  guestPortalColTeacher: "Instructor",
  guestPortalColStatus: "Status",
  guestPortalEmpty: "No appointments found.",
  guestPortalLoadingList: "Loading appointments…",
  guestPortalCancelConfirmTitle: "Cancel this appointment?",
  guestPortalCancelConfirmBody:
    "The appointment will be marked as cancelled. You may not be able to undo this depending on the policy.",
  guestPortalCancelConfirmBack: "Go back",
  guestPortalCancelConfirmSubmit: "Yes, cancel",
  bookingAssignTeacherLabel: "Instructor (substitution)",
  emailGuestPortalMagicSubject: "Your appointments at {siteName}",
  emailGuestPortalMagicGreeting: "Hello {name},",
  emailGuestPortalMagicIntro:
    "Use the link below to view appointments, cancel within the allowed window, and download invoices.",
  emailGuestPortalMagicCta: "Open my appointments",
  emailGuestPortalMagicFooter:
    "The link is valid for 7 days. Reply to this email if you need help.",
  emailBookingReminderSubject: "Reminder: appointment at {siteName}",
  emailBookingReminderGreeting: "Hello {name},",
  emailBookingReminderIntro: "This is a reminder for your appointment:",
  emailBookingReminderClosing: "We look forward to seeing you.",
  emailTeacherSubstitutionSubject: "Appointment reassigned — {siteName}",
  emailTeacherSubstitutionIntro: "The following appointment was assigned to another instructor.",
  emailTeacherSubstitutionBodyGuest: "Your appointment has a new instructor.",
  emailTeacherSubstitutionBodyOld: "You are no longer assigned as instructor for this appointment.",
  emailTeacherSubstitutionBodyNew: "You have been assigned as instructor for this appointment.",
  emailTeacherSubstitutionWas: "Previously:",
  emailTeacherSubstitutionNow: "Now:",
  payrollPdfGrossProductive: "Gross from productive hours",
  payrollPdfGrossInternal: "Gross from internal hours",
  payrollPdfWhtBasis: "Annual basis for withholding",
  payrollPdfSnapshotNote: "As finalized",
  payrollWeeklyHoursKvgLabel: "Weekly hours for KVG example (empty = 42)",
  payrollKvgAgeLabel: "KVG age band",
  payrollKvgAgeAdult: "Adult",
  payrollKvgAgeYouth: "Youth (16–20)",
  payrollApplyWhtLabel: "Apply 4 % withholding (if annual gross ≤ CHF 40,000)",
  payrollMerkblattAckLabel:
    "Confirmed: leaflet scope reviewed (e.g. annual wage under CHF 14,700 / no BVG obligation per leaflet)",
  payrollAhvNumberLabel: "AHV no. (optional)",
  payrollNotesLabel: "Internal note",
  payrollSaveProfile: "Save profile",
  payrollProfileSavedToast: "Payroll profile saved.",
  payrollProfileSaveFailed: "Could not save payroll profile.",
  payrollDownloadPdf: "Download PDF",
  payrollLoadError: "Could not load payroll.",
  payrollPdfNoComputation:
    "No calculation — set gross hourly wage in payroll profile.",
  payrollPdfTitle: "Payroll overview",
  payrollPdfNotAdvice: "Non-binding helper — statutory duties still apply.",
  payrollPdfSectionHours: "Hours",
  payrollPdfSectionEmployee: "Employee (deductions)",
  payrollPdfSectionEmployer: "Employer (costs, overview)",
  payrollRowGross: "Gross pay",
  payrollRowEmployeeSocial: "Social ins. EE (AHV/IV/FAK/ALV)",
  payrollRowWht: "Tax withholding (leaflet)",
  payrollWhtNotApplied: "not applied",
  payrollRowNetApprox: "Net payout (approx.)",
  payrollRowEmployerSocial: "Social ins. ER",
  payrollRowKvgEmployerMonth: "Health care ER share (month, leaflet example)",
  payrollPdfFooterMerkblatt: "Source / duties",
  payrollPdfFooterObligations:
    "Employer duties (filings, statements) must still be fulfilled independently of this overview.",
  timeLogCategoryBueroVerwaltung: "Office & admin",
  timeLogCategoryVorbereitung: "Preparation",
  timeLogCategoryMeeting: "Meetings",
  timeLogCategoryFortbildung: "Training",
  timeLogCategorySonstiges: "Other",
  adminMetricBookingsMonthLabelTemplate: "{bookingPlural} (month)",
  adminMetricBookingsMonthSub: "In the current calendar month",
  adminMetricRevenueLabel: "Revenue",
  adminMetricRevenueSub:
    "Sum of prices (excluding cancelled), current month",
  adminMetricActiveStaffLabelTemplate: "Active {staffCollectivePlural}",
  adminMetricGuestsTotalLabelTemplate: "{clientPlural} total",
  adminChartBookingsByMonthTitleTemplate:
    "{bookingPlural} per month ({year})",
  adminChartRevenueByStaffTitleTemplate:
    "Revenue per {staffCollectivePlural} (month)",
  adminChartRevenueByStaffHint:
    "Bars are relative to the highest revenue in the list",
  adminStatsTableHeaderChf: "CHF",
  adminUserListLoading: "Loading user list…",
  adminInviteEmailPlaceholder: "Email to invite",
  uiErrorHttpTemplate: "Error ({status})",
  adminSendMagicLink: "Send magic link",
  adminUsersEmptyHint:
    "No users yet. Enter an email above and send a magic link.",
  adminMagicLinkResentToast: "Magic link was sent again.",
  adminResendMagicLink: "Resend link",
  adminActivateUser: "Activate",
  adminActivateUserFailed: "Could not activate",
  adminCannotChangeOwnRoleHere: "You cannot change your own role here",
  adminRoleChangeFailed: "Could not change role",
  adminRoleToggle: "Toggle role",
  adminConfirmDeactivateUserTemplate:
    "Really deactivate {email}? They will no longer be able to sign in.",
  adminDeactivateUserFailed: "Could not deactivate",
  adminDeactivateUser: "Deactivate",
  labelRole: "Role",
  labelActive: "Active",
  uiYes: "yes",
  uiNo: "no",
  uiEmDash: "—",
  tableColAction: "Action",
  auditLogServerError: "Server error while loading the log.",
  auditLogHttpErrorTemplate: "HTTP {status}",
  auditLogLoadFailedPrefix: "Could not load log:",
  auditColTimeUtc: "Time (UTC)",
  auditColAction: "Action",
  auditColActor: "Actor",
  auditColResource: "Resource",
  auditColIp: "IP",
  auditColDetails: "Details",
  publicBookingCourseMetaTemplate:
    "{durationMin} min · max. {maxParticipants} · CHF {priceCHF}",
  invoicePdfVatTemplate: "VAT {percent}%",
  configResendApiKeyMissing:
    "RESEND_API_KEY is missing — magic link cannot be sent.",
  emailBookingRequestSubjectTemplate:
    "We received your {bookingRequest} — {siteName}",
  emailBookingRequestBodyLineTemplate:
    "Thank you for your {serviceSingular} request. We usually respond within 24 hours.",
  emailSignoffWithSiteTemplate: "Kind regards<br/>{siteName}",
  emailAdminNewRequestSubjectTemplate: "New {bookingRequest}: {guestName}",
  emailAdminNewRequestIntroTemplate: "New {bookingRequest} in the portal.",
  emailAdminNewRequestDateTimeLabel: "Date/time:",
  emailCtaOpenAdmin: "Open in admin",
  emailInviteSubjectTemplate: "Invitation to {siteName} — sign in",
  emailInviteGreetingTemplate: "Hello {name},",
  emailInviteBodyIntroTemplate:
    "You have been invited as {staffRole} for {siteName}. Use the link below to sign in (one-time use, approx. 24&nbsp;hours):",
  emailInviteCtaSignInTemplate: "Sign in to {siteName}",
  emailInviteLoginFallbackLineTemplate:
    "If the link expires, request a new magic link on the <a href=\"{loginUrl}\">sign-in page</a> using the same email address.",
  emailBookingConfirmedSubjectTemplate:
    "Your {serviceSingular} is confirmed — {siteName}",
  emailBookingConfirmedIntroTemplate: "Your {bookingSingular} is confirmed:",
  emailBookingConfirmedClosing: "We look forward to seeing you!",
} as const;

/** Team-channel demo lines for `npm run db:seed` when `NEXT_PUBLIC_HTML_LANG=en` */
export const DEMO_TEAM_CHANNEL_SEED_MESSAGES_EN = [
  "Welcome to the team channel!",
  "Please keep appointments up to date in the calendar.",
  "Questions? Contact an admin.",
  "Have a great weekend!",
  "Reminder: review booking requests in Admin.",
] as const;
